---
name: "integrations"
github: "jenkinsci/configuration-as-code-plugin"
paths:
- "io/jenkins/configuration-as-code/integrations"
developers:
- "praqma"
- "casz"
security:
  contacts:
    jira: "ewel"
