---
name: "configuration-as-code"
github: "jenkinsci/configuration-as-code-plugin"
paths:
- "org/jenkins-ci/plugins/configuration-as-code"
- "io/jenkins/configuration-as-code"
developers:
- "praqma"
- "casz"
security:
  contacts:
    jira: "ewel"
